### ISSUE TITLE
Directions on how to run project in IDEA

### ISSUE THREAD

**Issue by LinkedList** [yole/kxhtml-isomorphic#1]
Hi!

I am trying unsuccessfully to run this project in IDEA (even downloaded EAP build and EAP Kotlin plugin)
Could you possibly add some directions on how to proceed?

e.g. Idea complains: Error:(3, 14) Kotlin: Expected class 'Date' has no actual declaration in module 
even though the declarations are there and I can navigate to them.

and many more errors about unresolved references so I think I have something basic wrong about my setup.

**Comment by plannigan** [comment]
Agreed. I've been able to run the backend from graddle, but haven't had any success from Intellij. I haven't been able to figure our run configurations to run the backend or execute the tests (kotlin and javascript). I've also had cases where building the project fails:

> /home/xxx/kxhtml-isomorphic/frontend/src/main/kotlin/frontend.kt
> Error:(5, 40) Kotlin: Unresolved reference: Message
> Error:(6, 40) Kotlin: Unresolved reference: fromJSON
> Error:(7, 40) Kotlin: Unresolved reference: renderMessage
> Error:(55, 23) Kotlin: Unresolved reference: Message
> Error:(58, 13) Kotlin: Unresolved reference: renderMessage

The talk showed all of these things working, but it's not immediately obvious how to do it. Since the project files are not included in the repo, other people are forced to figure it out on their own.

I was hoping that I could use this project as a template for a side project I'd like to start. But not being able to replicate what was demonstrated is holding me back. In order to be a good example project for people looking to try out multi-platform projects, some documentation (beyond the generic multi-platform documentation) would be helpful. For example: explanation of how the various build.gradle files work together to specify dependencies on the other modules in the project.

**Comment by yole** [comment]
Added README with instructions.
